##### Students - [GET] getAllStudents()
GET http://localhost:8080/academics/api/students
Accept: application/json

##### Students - [GET] {String:username} getStudentDetails()
GET http://localhost:8080/academics/api/students/piet
Accept: application/json

##### Students - [GET] {String:username} getStudentDetails()
GET http://localhost:8080/academics/api/students/piet/subjects
Accept: application/json

##### Students - [GET] {String:username} getStudentDetails() (WILL FAIL DUE TO STUDENT NOT HAVING SUBJECTS)
GET http://localhost:8080/academics/api/students/inesmaria/subjects
Accept: application/json

##### Students - [POST] createNewStudent()
POST http://localhost:8080/academics/api/students
Content-Type: application/json

{
  "username": "john",
  "password": "jd",
  "name": "John Doe",
  "email": "johndoe@mail.com",
  "courseCode": 9123
}




##### Courses - [GET] getAllCourses()
GET http://localhost:8080/academics/api/courses
Accept: application/json

##### Courses - [POST] createNewCourse()
POST http://localhost:8080/academics/api/courses
Content-Type: application/json

{
  "code": 9147,
  "name": "Gestão (D)"
}